var questions = [
   {
      q: 'Q1. CIVIL ENGINEERING IS RELATED TO __________',
      options: ['BUILDINGS, DAMS & BRIDGES CONSTRUCTION ', 'FABRIC AND THEIR DESIGNING', 'PLANTS AND THEIR GROWTH', 'ELECTRICAL SYSTEM DESIGNING'],
      correct: 'BUILDINGS, DAMS & BRIDGES CONSTRUCTION' 
   },
   {
      q: 'Q2. WHAT IS THE FIRST STEP FOR EXECUTING CONSTRUCTION PLAN __________',
      options: ['PREPARE SITE DRAWINGS', 'PREPARE CONSTRUCTION INSTRUMENTS', 'READING SHEDULE', 'COST ESTIMATION'],
      correct: 'PREPARE SITE DRAWINGS' 
   },
   {
      q: 'Q3. WHEN FORCE APPLIED ON THE BEAM __________',
      options: ['FLEXURAL STRESSES PRODUCED', 'SHEAR STRESSES PRODUCED', 'NORMAL STRESSES PRODUCED', 'ALL OF THEM'],
      correct: 'ALL OF THEM' 
   },
   {
      q: 'Q4. STAIR IS STRUCTURAL ELEMENT?',
      options: ['TRUE', 'FALSE'],
      correct:  'TRUE'
   
   },
   {
      q: 'Q5. ASTM IS __________',
      options: ['AMERICAN STANDARD', 'BRITISH STANDARD', 'GERMAN STANDARD', 'NONE OF THE ABOVE'],
      correct: 'AMERICAN STANDARD' 
   }
]